# Generated by Django 4.1.1 on 2022-09-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='F1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=4)),
                ('round', models.CharField(max_length=2)),
                ('circuit', models.CharField(max_length=240)),
                ('country', models.CharField(max_length=240)),
                ('date', models.DateField()),
            ],
        ),
    ]
