# Generated by Django 4.1.1 on 2022-09-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='F1',
            new_name='F1Season',
        ),
    ]
