# Generated by Django 4.1.1 on 2022-09-11 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0002_rename_f1_f1season'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='F1Season',
            new_name='F1Race',
        ),
    ]
